### PR TITLE
spacing issue in command setup.

### PR DESCRIPTION
**Pull request by greenleeuw**
this should be the only command that has issues, as mentioned [Here](https://github.com/ZeldaCraft-MC/denizen-scripts/issues/78)

However if the other also have issues its probably something to do with the definemap

### CODE REVIEW

**Comment by mergu** [comment]
I only posted the one, but all of these errored

**Comment by mergu** [comment]
```
ERROR in script 'mute_cmd_run_once' in queue 'MUTE_CMD_RUN_ONCE_208856403_SubsectionOrlando'
      while executing command 'discordcommand' in file 'scripts/bot-stuff/slash_command_templates.dsc' on line '725'
      with attached player 'p@4f1e61de-6f0c-46aa-8c26-52354c4bd9cc (Mergu)'

ERROR Woah! Invalid arguments were specified!
<FORCE_ALIGN>Must have an instruction!

=== Definitions ===

<[options]> == map@[1=map@[type=string;name=ign;description=What is the persons ign (in game name);required=true];2...

=== Full Script ===

mute_cmd_run_once:
  type: task
  debug: false
  script:
    - definemap options:
        1:
          type: string
          name: ign
          description: What is the persons ign (in game name)
          required: true
        2:
          type: string
          name: time
          description: what is the time of this tempban
          required: true
          choices:
            1:
              name: 5 minutes
              type: 5m
            2:
              name: 10 minutes
              type: 10m
            3:
              name: 30 minutes
              type: 30m
            4:
              name: 1 hour
              type: 1h
            5:
              name: 2 hours
              type: 2h
>   - ~discordcommand id:zc-info group:<discord[zc-info].group[<script[zc_bot_info].data_key[group_name]>]> name:mute "description:Mute a player ingame" options:<[options]>
```

**Comment by mergu** [comment]
```
ERROR in script 'warn_cmd_run_once' in queue 'WARN_CMD_RUN_ONCE_208849645_WashingChair'
      while executing command 'discordcommand' in file 'scripts/bot-stuff/slash_command_templates.dsc' on line '692'
      with attached player 'p@4f1e61de-6f0c-46aa-8c26-52354c4bd9cc (Mergu)'

ERROR Woah! Invalid arguments were specified!
<FORCE_ALIGN>Must have an instruction!

=== Definitions ===

<[options]> == map@[1=map@[type=string;name=ign;description=What is the persons ign (in game name);required=true];2...

=== Full Script ===

warn_cmd_run_once:
  type: task
  debug: false
  script:
    - definemap options:
        1:
          type: string
          name: ign
          description: What is the persons ign (in game name)
          required: true
        2:
          type: string
          name: reason
          description: What is the reason of the tempban
          required: true
>   - ~discordcommand id:zc-info group:<discord[zc-info].group[<script[zc_bot_info].data_key[group_name]>]> name:warn "description:Warn a player" options:<[options]>
```

**Comment by mergu** [comment]
```
ERROR in script 'tempban_cmd_run_once' in queue 'TEMPBAN_CMD_RUN_ONCE_208835896_AudioGym'
      while executing command 'discordcommand' in file 'scripts/bot-stuff/slash_command_templates.dsc' on line '658'
      with attached player 'p@4f1e61de-6f0c-46aa-8c26-52354c4bd9cc (Mergu)'

ERROR Woah! Invalid arguments were specified!
<FORCE_ALIGN>Must have an instruction!

=== Definitions ===

<[options]> == map@[1=map@[type=string;name=ign;description=What is the persons ign (in game name);required=true];2...

=== Full Script ===

tempban_cmd_run_once:
  type: task
  debug: false
  script:
    - definemap options:
        1:
          type: string
          name: ign
          description: What is the persons ign (in game name)
          required: true
        2:
          type: string
          name: reason
          description: What is the reason of the tempban
          required: true
        3:
          type: string
          name: time
          description: what is the time of this tempban
          required: true
          choices:
            1:
              name: 1 hour
              type: 1h
            2:
              name: 1 day
              type: 1d
            3:
              name: 3 days
              type: 3d
            4:
              name: 5 days
              type: 5d
            5:
              name: 7 days
              type: 7d
            6:
              name: 2 weeks
              type: 14d
            7:
              name: 1 month
              type: 31d
            8:
              name: 2 months
              type: 62d
>   - ~discordcommand id:zc-info group:<discord[zc-info].group[<script[zc_bot_info].data_key[group_name]>]> name:tempban "description:Tempban a player for a certain time" options:<[options]>
```

**Comment by mergu** [comment]
This specific error is caused by not having `[create/perms/delete]` in the command after the id. So this should fix it:
```
- ~discordcommand id:zc-info create ...
```

**Comment by greenleeuw** [comment]
woop i am smart

**Comment by mergu** [comment]
Good catch on the spacing though

**Review by mergu — APPROVED** [review]
Thank you ❤️

**Pull request merged**
